# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Pagination
paginate: 2
paginate_path: blog/page:num


# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research
- title: CV
  url: /cv
- title: Code and Data
  url: /data


# Site settings
url: 'https://tbmiller-astro.github.io'
baseurl: ''
title: 'Tim Miller'
description: 'Tim Miller`s personal research website'
permalink: pretty
# logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

